# Generated by Django 4.1 on 2022-10-23 02:23

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUB', 'Submarino'), ('CRU', 'Crucero'), ('GUER', 'Barco de guerra'), ('AVI', 'Avion')], max_length=50)),
                ('body_length', models.PositiveSmallIntegerField()),
                ('head_position', models.CharField(max_length=10)),
                ('direction', models.CharField(choices=[('N', 'north'), ('S', 'south'), ('W', 'west'), ('E', 'east')], max_length=1)),
            ],
            options={
                'verbose_name': 'Ship',
                'verbose_name_plural': 'Ships',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PRI', 'private'), ('PUB', 'public')], max_length=6)),
                ('active', models.BooleanField()),
                ('code', models.CharField(max_length=6)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.user')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.CharField(max_length=250)),
                ('game_configuration', models.JSONField(default=game.models.Game.game_configuration, verbose_name='GameConfiguration')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='game.room')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
