# Generated by Django 4.1 on 2022-10-30 05:20

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_game_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardship',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_ships', to='game.board'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_configuration',
            field=models.JSONField(default=game.models.Game.game_configuration, verbose_name='GameConfiguration'),
        ),
    ]
