# Generated by Django 4.1 on 2022-10-23 01:54

import core.game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_game_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_configuration',
            field=models.JSONField(default=core.game.models.Game.game_configuration, verbose_name='GameConfiguration'),
        ),
    ]
